### ISSUE TITLE
Possible to unlock more graphic settings?

### ISSUE THREAD

**Issue by guinaicha** [Nenkai/GBFRDataTools#2]
I realize the tool's main focus may be visual mods, but just in case, is it possible by unpacking everything, to reveal more graphics settings not available by default?

Settings like, Shadow, Post-Process, Ambient Occlusion, View Distance, AA to name a few. I'm also keen to make visual mods, so if there's anyway I/we can contribute, please do let us know. I saw the filelist.txt and used v0.1.0 to list the files but it's all a blur atm.

**Comment by Nenkai** [comment]
I wouldn't know personally as I have yet to get the actual game; only the necessary files to understand the whole archive were provided to me.

The current file list should contain most core/critical files considering they were dumped at runtime by somebody else.

If I had to guess, maybe somewhere in the system folder?
