### ISSUE TITLE
Extract All only gives "unk_#####" filenames

### ISSUE THREAD

**Issue by Demonslayerx8** [Nenkai/GBFRDataTools#4]
doing "extract all" option doesn't spit the files out properly? Only gives me files named "unk_###" with no proper filenames or directories that's shown in the filelist.

edit:
did extract option to point to a file, still gives "unk" filename.
![image](https://github.com/Nenkai/GBFRDataTools/assets/17195757/141a0ce8-ad50-4c8e-8b04-8097ea0c931a)

**Comment by WistfulHopes** [comment]
this has been fixed in the most recent commit, either wait for a release or build yourself

**Comment by WistfulHopes** [comment]
new release up
