### ISSUE TITLE
The GBFRDataTools.exe keeps crashing.

### ISSUE THREAD

**Issue by ldslovemagic** [Nenkai/GBFRDataTools#9]
The GBFRDataTools.exe keeps crashing.WIN10 system.
![tool0](https://github.com/Nenkai/GBFRDataTools/assets/24726481/30759877-874b-439f-b156-cbbc50409fb1)

![tool](https://github.com/Nenkai/GBFRDataTools/assets/24726481/3a1af60e-eda7-48fd-bf90-0edf453b7f9b)

**Comment by modusc896d352** [comment]
seems (to me at least) like you just ran an executable straight from the explorer instead of the command-line

**Comment by ldslovemagic** [comment]
I am sorry.I don't know how to use it.I tried to open it with Microsoft Visual Studio 2022,but I couldn't read it.
![01](https://github.com/Nenkai/GBFRDataTools/assets/24726481/92382d77-d84e-48b8-9d7f-ec36c374c24d)

![02](https://github.com/Nenkai/GBFRDataTools/assets/24726481/666520d4-4a0e-489b-a750-4d427b9aa68e)

**Comment by modusc896d352** [comment]
tbh i haven't used the tool either, but you need to specify where **data.i** _is_ instead of **data.1**, otherwise the tool will simply not work for you

**Comment by ldslovemagic** [comment]
Thanks for the reminder.I can extract it.
